### ISSUE TITLE
Example code where Combine implements a Flow coming from Swift into Kotlin

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/ZenhubDefault#9]
Generally when we talk about reactive code between Kotlin and Swift, we're thinking from Kotlin to Swift. What would it look like the other way? We pass something from Swift into Kotlin that exposes a "Flow". That Flow is backed by a Combine structure.

We should not worry about the boilerplate or casting involved. Assume there will be some Swift-side ugliness, and there can be a bit on the Kotlin side too, but ideally we can push a reactive structure into Kotlin code.

Just sample and quick write up on feasibility. This is kind of for Cash App, although I'm not sure it'll be done in time for them to use it, but I'd like to think through this anyway.

**Comment by russhwolf** [comment]
Here's a branch trying this out with the SwiftCoroutines repo from my old interop stuff
https://github.com/touchlab/SwiftCoroutines/tree/reverse-interop

**Comment by russhwolf** [comment]
Having issues in the current setup where things get dropped when multiple events come in at the same time. Seems to work alright when events are separated by delays (ie with `asyncAfter()` calls in Swift, in this example)

**Comment by kpgalligan** [comment]
I'm going to close this for now. The Cash folks did something hakcy, so we can just close this but keet it around for reference if needed

**Comment by russhwolf** [comment]
Yeah that makes sense. If we decide to do our own codegen thing then this would be a cool piece to revisit and add to that.
